kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: currencyexchange
  labels:
    app: currencyexchange
    app.kubernetes.io/component: currencyexchange
    app.kubernetes.io/instance: currencyexchange
    app.kubernetes.io/part-of: bee-travels
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: currencyexchange
    deploymentconfig: currencyexchange
  template:
    metadata:
      labels:
        app: currencyexchange
        deploymentconfig: currencyexchange
    spec:
      containers:
        - name: currencyexchange
          image: ${DOCKERHUB_NAME}/currencyexchange:latest
          ports:
            - containerPort: 9201
              protocol: TCP
          env:
            - name: HOST_IP
              value: currencyexchange
            - name: PORT
              value: '9201'
            - name: SCHEME
              value: http
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: INSTANA_AGENT_PORT
              value: '42699'
            - name: INSTANA_SERVICE_NAME
              value: currencyexchange
            - name: INSTANA_AUTOPROFILE
              value: "true"
            - name: INSTANA_LOG_LEVEL
              value: "warn"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
