kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: hotel-v1-python
  labels:
    app: hotel-v1-python
    app.kubernetes.io/component: hotel-v1-python
    app.kubernetes.io/instance: hotel-v1-python
    app.kubernetes.io/part-of: bee-travels
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 256Mi
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: hotel-v1-python
    deploymentconfig: hotel-v1-python
  template:
    metadata:
      labels:
        app: hotel-v1-python
        deploymentconfig: hotel-v1-python
    spec:
      containers:
        - name: hotel-v1-python
          image: ${DOCKERHUB_NAME}/python-hotel-v1:latest
          ports:
            - containerPort: 9101
              protocol: TCP
          env:
            - name: HOST_IP
              value: hotel-v1-python
            - name: LOG_LEVEL
              value: info
            - name: PORT
              value: '9101'
            - name: SCHEME
              value: http
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: INSTANA_AGENT_PORT
              value: '42699'
            - name: INSTANA_SERVICE_NAME
              value: hotel-v1-python
            - name: INSTANA_AUTOPROFILE
              value: "true"
            - name: INSTANA_LOG_LEVEL
              value: "warn"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
